spring:

  profiles:
    active: dev
  devtools:
    restart: true
  livereload:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/hayequipo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: gonza123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create

  server:
    port: 8080


  mail:
    host: smtp.gmail.com
    port: 587
    username: gonza.zago@gmail.com
    password: gonza123
    tls: true
    properties.mail.smtp:
                auth: true
                starttls.enable: true
                ssl.trust: smtp.gmail.com
